export const SIGNUP_LOGIN = "SIGNUP_LOGIN";
export const AUTHENTICATE = "AUTHENTICATE";

export const LOGIN_USER_DETAILS_EMAIL = "LOGIN_USER_DETAILS_EMAIL";
export const LOGIN_USER_DETAILS_NAME = "LOGIN_USER_DETAILS_NAME";
export const LOGIN_USER_DETAILS_PASSWORD = "LOGIN_USER_DETAILS_PASSWORD";
export const CHECK_USER = "CHECK_USER";

export const ADD_TODO = "ADD_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const GET_TODO = "GET_TODO";
export const TODO_LIST = "TODO_LIST";
